// <auto-generated />
using System;
using AolDevicesConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AolDevicesConfig.Migrations
{
    [DbContext(typeof(ConfigContext))]
    partial class ConfigContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AolDevicesConfig.ConfigParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ParameterName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConfigParameters");
                });

            modelBuilder.Entity("AolDevicesConfig.DeviceConfigParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigParameter")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceConfiguration")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigParameter");

                    b.HasIndex("DeviceConfiguration");

                    b.ToTable("DeviceConfigParameters");
                });

            modelBuilder.Entity("AolDevicesConfig.DeviceConfiguration", b =>
                {
                    b.Property<int>("ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PID")
                        .HasColumnType("text");

                    b.Property<string>("PIDConfig")
                        .HasColumnType("text");

                    b.HasKey("ConfigID");

                    b.ToTable("DeviceConfigurations");
                });

            modelBuilder.Entity("AolDevicesConfig.DeviceConfigParameter", b =>
                {
                    b.HasOne("AolDevicesConfig.ConfigParameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ConfigParameter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AolDevicesConfig.DeviceConfiguration", "DeviceConfig")
                        .WithMany()
                        .HasForeignKey("DeviceConfiguration")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceConfig");

                    b.Navigation("Parameter");
                });
#pragma warning restore 612, 618
        }
    }
}
